### ISSUE TITLE
opening an episode page on a vertical screen results in squished text that doesn't unsquish when table of contents is minimized

### ISSUE THREAD

**Issue by rbavery** [carpentries/workbench#64] opened 2023-08-04 18:42 UTC
this isn't super pressing, since using vertical screens isn't common in a workshop setting. But when I open an episode on a vert screen, text gets squished. and it doesn't expand to take the full screen space when the table of contents is minimized.

https://esciencecenter-digital-skills.github.io/geospatial-python/11-parallel-raster-computations.html

![Selection_039](https://github.com/carpentries/workbench/assets/22258697/bdea4f7b-4c7a-4147-b076-98ff65933697)
![Selection_040](https://github.com/carpentries/workbench/assets/22258697/78f5bd93-306d-41fc-8cd0-f31bd86315a0)

cc @fnattino @rogerkuou

**Comment by zkamvar** [comment] 2023-08-04 22:03
Hi @rbavery, this looks like the same issue as #57 and I'm afraid I cannot reproduce it. Do you see the same behaviour in an incognito window? 

cc: @tobyhodges

**Comment by rbavery** [comment] 2023-08-05 01:15
ah sorry about that. I looked at the issue and I couldn't reproduce it either when minimizing the window on a wide screen. To reproduce, I was opening the webpage on a vertical screen.

the issue doesn't happen when I paste the link into an incognito window for some reason. and after I disable all my adblock extensions and dark reader extensions and then re-enable them, I can't reproduce the issue. So I'm not sure which or how extensions are causing the issue but they seem to be the culprit here.

**Comment by zkamvar** [comment] 2023-08-07 14:15
Thank you for following up with these details. This does help a bit because it confirms that it's an extension that's doing it. 

IIRC, extensions work by manipulating the page contents to insert JS, HTML, or CSS. There is likely a clash of attributes that is happening with one of the extensions and The Workbench. 

That being said, it's one of those frustrating problems that we cannot address until we figure out how to reproduce it. The only thing I would suggest is that the next time this happens, open the page in an incognito window (or in another browser), open an inspector, and then see if you can spot any differences in the `<head>` or `<footer>` elements.

**Comment by froggleston** [comment] 2024-06-14 10:01
Fixed in https://github.com/carpentries/varnish/pull/109

**Closed by froggleston** 2024-06-14 10:01 UTC
Labels: duplicate
