### ISSUE TITLE
Improve readability of the Episode overview

### ISSUE THREAD

**Issue by drmowinckels** [carpentries/workbench#57] opened 2023-06-05 07:10 UTC
The overview at the start of an episode is really hard to read in desktop mode when the episode menu is expanded. If `Expand All Solutions` was moved to another location, so that the Overview can utilise the entire parent div, I think this would improve it by a lot.

![image](https://github.com/carpentries/workbench/assets/14014329/f9581e60-f43b-4c53-935d-92b493c812ae)

Alternatively, you could set the child divs in the Overview to be rows rather than columns, so that they are always stacked vertically rather than horizontally. But that will not look great when the episode menu is collapsed.

In terms of suggestions to where the expand all solutions could be, I think it could fit in the Episode menu or right below the Overview. I also think it could benefit from getting some styling, like being a button or something.

**Comment by zkamvar** [comment] 2023-06-16 18:48
Thank you for opening this and providing suggestions, @drmowinckels. 

This is part of a broader sticky issue that currently exists in https://github.com/carpentries/varnish/issues/83, https://github.com/carpentries/sandpaper/issues/299, and https://github.com/carpentries/workbench/discussions/10#discussioncomment-2938302

We are still running a bit of a backlog at the moment, so it may take some time for this to get resolved.

**Comment by drmowinckels** [comment] 2023-06-16 20:54
Sorry for missing other places where this is mentioned.

I'm pretty naive to lua filters, so I cant really grasp it completely, but from the code [here](https://github.com/carpentries/sandpaper/blob/14e7cbc59579ebcf51d08b9e1d9975e7cd61d5ff/inst/rmarkdown/lua/lesson.lua#L61-L102) I think I get the gist of what is going on.

So, if Objectives and Questions are set as bootstrap cards, could you not have them in a row div, and have them wrap on top of each other when needed through bootstrap columns of even a flex container?

I think doing that, and moving the expansion to its own "row" would make the behaviour of that block much neater. 

That being said, I can see its a finicky one to solve.

**Comment by zkamvar** [comment] 2023-06-16 21:29
> Sorry for missing other places where this is mentioned.

Absolutely no apologies are necessary in this (and most other) cases. Distributed issues is one of the challenges of having a modular toolchain. 

Would you be able to provide the link to the page along with the browser you are using and the width of your window? I'm finding that I cannot reproduce this behavior in Chrome with this episode as I narrow the window

![screenshot gif of a browser window open and slowly being narrowed and widened](https://github.com/carpentries/workbench/assets/3639446/cdf9c92d-6a76-461e-9f1f-8f776118c3ec)

You are correct that that is the right place to modify is the lua filter along with [the overview.scss file in {varnish}](https://github.com/carpentries/varnish/blob/main/source/stylesheets/overview.scss). 

One of the challenges we faced is that the implementation of the overview card was not designed in a flexible manner and this has caused all these issues that we are seeing (the questions column is specified to be half the width of the objectives and that seems... wrong).

**Comment by zkamvar** [comment] 2023-06-19 13:23
I now have the same version of Chrome and I do not see this -_-

@tobyhodges, I know you have a more recent Mac, can you check this behaviour on your machine?

**Comment by drmowinckels** [comment] 2023-06-20 19:12
right-o! I tried in incognito and the overview is looking so much better! Much more like yours. I still think the questions section should have a little more space, but its not like it was at all. I try to figure out which specific extension might be doing it and get back to you.

**Comment by froggleston** [comment] 2023-11-30 11:51
I've been looking at this again, and there's some interesting behaviour related to the `.card-title` font sizing. At font-size 24px, the default, I see the reported behaviour.

However, upon reducing the `.card-title` font-size to 22px, the problem goes away:
![font_sizing](https://github.com/carpentries/workbench/assets/1872302/b74c723d-7a59-4efa-9637-c17d7f3a6b61)

This makes me wonder that it's a screen resolution vs browser window size font scaling issue rather than a particular class or CSS property messing with anything. Looking at varnish's `overview.scss` it seems that the .card-title font-size is fixed. Could a solution be to use the `$font-sizes` sass map to automatically scale heading text (https://getbootstrap.com/docs/5.0/utilities/text/#maps)?

**Comment by ErinBecker** [comment] 2024-07-09 17:39
Fixed with https://github.com/carpentries/varnish/pull/109

**Closed by ErinBecker** 2024-07-09 17:39 UTC
Labels: bug, {sandpaper}, {varnish}
